[package]
name = "wasted_time"
version = "0.2.0"
authors = ["Florian Anderiasch <fa@art-core.org>"]

[[bin]]
name = "WastedTime"
path = "src/main.rs"

[dependencies]
kernel32-sys = "0.2.2"
serde_json = "1.0"
time = "0.1.38"
user32-sys = "0.1.2"
winapi = "0.2.8"