[WastedTime]
# ignorelist: if the window matches, it will not be recorded at all
# ignorelist format: ["title", "class", "path", "name"]
ignorelist = [ ["", "", "SomethingSomething\\.exe$", ""] ]

# grouplist: if the window matches, only the "name" will be displayed
# grouplist format: ["title", "class", "path", "name"]
grouplist = [ [" Mozilla Firefox$", "", "firefox\\.exe$", "Firefox"] ]

debug = "false"